In [1]:
#importing libraries
import numpy as np  
import matplotlib.pyplot as mtp  
import pandas as pd  

In [2]:
#data fetching
data = pd.read_csv('Social_Network_Ads.csv')

In [3]:
data.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [33]:
data.describe()

User ID      Gender         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000  400.000000       400.000000  400.000000
mean   1.569154e+07    0.490000   37.655000     69742.500000    0.357500
std    7.165832e+04    0.500526   10.482877     34096.960282    0.479864
min    1.556669e+07    0.000000   18.000000     15000.000000    0.000000
25%    1.562676e+07    0.000000   29.750000     43000.000000    0.000000
50%    1.569434e+07    0.000000   37.000000     70000.000000    0.000000
75%    1.575036e+07    1.000000   46.000000     88000.000000    1.000000
max    1.581524e+07    1.000000   60.000000    150000.000000    1.000000

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Gender']= le.fit_transform(data['Gender']) 

In [5]:
 x= data.iloc[:,:4].values  

In [6]:
print(x)

[[15624510        1       19    19000]
 [15810944        1       35    20000]
 [15668575        0       26    43000]
 ...
 [15654296        0       50    20000]
 [15755018        1       36    33000]
 [15594041        0       49    36000]]


In [7]:
y= data.iloc[:, 4].values 

In [8]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)

In [11]:
print(x_train)

[[15810075        0       44    39000]
 [15583681        1       32   120000]
 [15733964        0       38    50000]
 ...
 [15591433        1       36    52000]
 [15776348        0       27    54000]
 [15794661        0       26   118000]]


In [12]:
print(y_train)

[0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 0 0]


In [13]:
print(x_test)

[[15725660        1       30    87000]
 [15652400        0       38    50000]
 [15776844        1       35    75000]
 [15738448        0       30    79000]
 [15638003        0       35    50000]
 [15814004        1       27    20000]
 [15610140        0       31    15000]
 [15680587        1       36   144000]
 [15666141        0       18    68000]
 [15622478        1       47    43000]
 [15689425        1       30    49000]
 [15800061        0       28    55000]
 [15773447        1       37    55000]
 [15579212        1       39    77000]
 [15746139        1       20    86000]
 [15789109        0       32   117000]
 [15760570        1       37    77000]
 [15807909        1       19    85000]
 [15654230        0       55   130000]
 [15708228        1       35    22000]
 [15609653        0       35    47000]
 [15746203        0       47   144000]
 [15678168        0       41    51000]
 [15729908        1       47   105000]
 [15614420        0       23    28000]
 [15753861        0      

In [14]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
st_x= StandardScaler()  

In [17]:
x_train= st_x.fit_transform(x_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [18]:
print(x_train)

[[ 1.67009484 -0.98019606  0.58164944 -0.88670699]
 [-1.52442817  1.02020406 -0.60673761  1.46173768]
 [ 0.59613378 -0.98019606 -0.01254409 -0.5677824 ]
 ...
 [-1.4150439   1.02020406 -0.21060859 -0.50979612]
 [ 1.19419143 -0.98019606 -1.10189888 -0.45180983]
 [ 1.45259625 -0.98019606 -1.20093113  1.40375139]]


In [19]:
x_test= st_x.transform(x_test) 

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [20]:
print(x_test)

[[ 4.78960539e-01  1.02020406e+00 -8.04802115e-01  5.04963926e-01]
 [-5.54771608e-01 -9.80196059e-01 -1.25440855e-02 -5.67782405e-01]
 [ 1.20119022e+00  1.02020406e+00 -3.09640847e-01  1.57046197e-01]
 [ 6.59405075e-01 -9.80196059e-01 -8.04802115e-01  2.73018773e-01]
 [-7.57919871e-01 -9.80196059e-01 -3.09640847e-01 -5.67782405e-01]
 [ 1.72553483e+00  1.02020406e+00 -1.10189888e+00 -1.43757673e+00]
 [-1.15107956e+00 -9.80196059e-01 -7.05769861e-01 -1.58254245e+00]
 [-1.57040131e-01  1.02020406e+00 -2.10608593e-01  2.15757314e+00]
 [-3.60879806e-01 -9.80196059e-01 -1.99318916e+00 -4.59058115e-02]
 [-9.76984730e-01  1.02020406e+00  8.78746198e-01 -7.70734413e-01]
 [-3.23319037e-02  1.02020406e+00 -8.04802115e-01 -5.96775549e-01]
 [ 1.52879272e+00 -9.80196059e-01 -1.00286662e+00 -4.22816685e-01]
 [ 1.15325699e+00  1.02020406e+00 -1.11576339e-01 -4.22816685e-01]
 [-1.58748780e+00  1.02020406e+00  8.64881682e-02  2.15032485e-01]
 [ 7.67928607e-01  1.02020406e+00 -1.79512465e+00  4.75970782e

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
classifier= LogisticRegression(random_state=0)  
classifier.fit(x_train, y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [23]:
y_pred= classifier.predict(x_test)

In [24]:
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1]


In [25]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
cm= confusion_matrix(y_test,y_pred)

In [28]:
print("confusion matrix:",cm)

confusion matrix: [[65  3]
 [ 8 24]]


In [29]:
from sklearn.metrics import accuracy_score 

In [30]:
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.89


In [ ]:
from matplotlib.colors import ListedColormap  
x_set, y_set = x_test, y_test  
x1, x2 = np.meshgrid(np.arange(start = x_set[:, 0].min() - 1, stop = x_set[:, 0].max() + 1, step  =0.01),  
np.arange(start = x_set[:, 1].min() - 1, stop = x_set[:, 1].max() + 1, step = 0.01))  
mtp.contourf(x1, x2, classifier.predict(np.array([x1.ravel(), x2.ravel()]).T).reshape(x1.shape),  
alpha = 0.75, cmap = ListedColormap(('white','grey' )))  
mtp.xlim(x1.min(), x1.max())  
mtp.ylim(x2.min(), x2.max())  
for i, j in enumerate(np.unique(y_set)):  
    mtp.scatter(x_set[y_set == j, 0], x_set[y_set == j, 1],  
        c = ListedColormap(('red', 'blue'))(i), label = j)  
mtp.title('Logistic Regression (Test set)')  
mtp.xlabel('Age')  
mtp.ylabel('Estimated Salary')  
mtp.legend()  
mtp.show() 