In [1]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd

In [2]:
data = pd.read_csv('tennis.csv')

In [3]:
data

outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['outlook']= le.fit_transform(data['outlook']) 
data['temp']= le.fit_transform(data['temp'])
data['humidity']= le.fit_transform(data['humidity'])
data['windy']= le.fit_transform(data['windy'])
data['play']= le.fit_transform(data['play']) 

In [5]:
data

outlook  temp  humidity  windy  play
0         2     1         0      0     0
1         2     1         0      1     0
2         0     1         0      0     1
3         1     2         0      0     1
4         1     0         1      0     1
5         1     0         1      1     0
6         0     0         1      1     1
7         2     2         0      0     0
8         2     0         1      0     1
9         1     2         1      0     1
10        2     2         1      1     1
11        0     2         0      1     1
12        0     1         1      0     1
13        1     2         0      1     0

In [6]:
x = data.iloc[:,:4].values 

In [7]:
x

array([[2, 1, 0, 0],
       [2, 1, 0, 1],
       [0, 1, 0, 0],
       [1, 2, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 0, 1, 1],
       [2, 2, 0, 0],
       [2, 0, 1, 0],
       [1, 2, 1, 0],
       [2, 2, 1, 1],
       [0, 2, 0, 1],
       [0, 1, 1, 0],
       [1, 2, 0, 1]], dtype=int64)

In [8]:
y = data.iloc[:, 4].values

In [9]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [12]:
x_train

array([[0, 1, 0, 0],
       [1, 2, 0, 1],
       [1, 2, 1, 0],
       [2, 1, 0, 1],
       [2, 2, 0, 0],
       [2, 2, 1, 1],
       [1, 2, 0, 0],
       [2, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 1, 1, 0]], dtype=int64)

In [13]:
x_test

array([[2, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 0, 1, 0],
       [0, 2, 0, 1]], dtype=int64)

In [14]:
y_train

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1])

In [15]:
y_test

array([1, 1, 1, 1])

In [16]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
x_train = sc.fit_transform(x_train) 
x_test = sc.transform(x_test) 

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [17]:
x_train

array([[-1.60356745, -0.60302269, -0.81649658, -0.81649658],
       [-0.26726124,  0.90453403, -0.81649658,  1.22474487],
       [-0.26726124,  0.90453403,  1.22474487, -0.81649658],
       [ 1.06904497, -0.60302269, -0.81649658,  1.22474487],
       [ 1.06904497,  0.90453403, -0.81649658, -0.81649658],
       [ 1.06904497,  0.90453403,  1.22474487,  1.22474487],
       [-0.26726124,  0.90453403, -0.81649658, -0.81649658],
       [ 1.06904497, -0.60302269, -0.81649658, -0.81649658],
       [-0.26726124, -2.11057941,  1.22474487,  1.22474487],
       [-1.60356745, -0.60302269,  1.22474487, -0.81649658]])

In [18]:
x_test

array([[ 1.06904497, -2.11057941,  1.22474487, -0.81649658],
       [-1.60356745, -2.11057941,  1.22474487,  1.22474487],
       [-0.26726124, -2.11057941,  1.22474487, -0.81649658],
       [-1.60356745,  0.90453403, -0.81649658,  1.22474487]])

In [19]:
from sklearn.naive_bayes import GaussianNB 
classifier = GaussianNB() 
classifier.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [20]:
y_pred = classifier.predict(x_test)

In [21]:
y_pred

array([0, 1, 0, 1])

In [22]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.5


In [26]:
df = pd.DataFrame(y_test, y_pred)

In [27]:
df

0
0  1
1  1
0  1
1  1

In [28]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred)

In [29]:
cm

array([[0, 0],
       [2, 2]], dtype=int64)