In [1]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler

In [2]:
data= pd.read_csv('Social_Network_Ads.csv')

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Gender']= le.fit_transform(data['Gender']) 

In [4]:
x= data.iloc[:,:4].values 

In [5]:
x

array([[15624510,        1,       19,    19000],
       [15810944,        1,       35,    20000],
       [15668575,        0,       26,    43000],
       ...,
       [15654296,        0,       50,    20000],
       [15755018,        1,       36,    33000],
       [15594041,        0,       49,    36000]], dtype=int64)

In [6]:
y= data.iloc[:, 4].values

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [8]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)

In [9]:
st_x= StandardScaler()

In [10]:
x_train= st_x.fit_transform(x_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [11]:
x_test= st_x.transform(x_test) 

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [12]:
x_train

array([[ 1.67009484, -0.98019606,  0.58164944, -0.88670699],
       [-1.52442817,  1.02020406, -0.60673761,  1.46173768],
       [ 0.59613378, -0.98019606, -0.01254409, -0.5677824 ],
       ...,
       [-1.4150439 ,  1.02020406, -0.21060859, -0.50979612],
       [ 1.19419143, -0.98019606, -1.10189888, -0.45180983],
       [ 1.45259625, -0.98019606, -1.20093113,  1.40375139]])

In [13]:
x_test

array([[ 4.78960539e-01,  1.02020406e+00, -8.04802115e-01,
         5.04963926e-01],
       [-5.54771608e-01, -9.80196059e-01, -1.25440855e-02,
        -5.67782405e-01],
       [ 1.20119022e+00,  1.02020406e+00, -3.09640847e-01,
         1.57046197e-01],
       [ 6.59405075e-01, -9.80196059e-01, -8.04802115e-01,
         2.73018773e-01],
       [-7.57919871e-01, -9.80196059e-01, -3.09640847e-01,
        -5.67782405e-01],
       [ 1.72553483e+00,  1.02020406e+00, -1.10189888e+00,
        -1.43757673e+00],
       [-1.15107956e+00, -9.80196059e-01, -7.05769861e-01,
        -1.58254245e+00],
       [-1.57040131e-01,  1.02020406e+00, -2.10608593e-01,
         2.15757314e+00],
       [-3.60879806e-01, -9.80196059e-01, -1.99318916e+00,
        -4.59058115e-02],
       [-9.76984730e-01,  1.02020406e+00,  8.78746198e-01,
        -7.70734413e-01],
       [-3.23319037e-02,  1.02020406e+00, -8.04802115e-01,
        -5.96775549e-01],
       [ 1.52879272e+00, -9.80196059e-01, -1.00286662e+00,
      

In [14]:
from sklearn.svm import SVC

In [15]:
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [16]:
y_pred= classifier.predict(x_test)

In [17]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [18]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [19]:
df = pd.DataFrame(y_test,y_pred)

In [20]:
df.head(10)

0
0  0
0  0
0  0
0  0
0  0
0  0
0  0
1  1
0  0
1  0

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
cm= confusion_matrix(y_test, y_pred)

In [23]:
cm

array([[64,  4],
       [ 8, 24]], dtype=int64)

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.88
